[package]
name = "wgpu-learn"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
winit = {version ="0.30", features = ["rwh_05" ] }
wgpu = "22" #locked to egui
bytemuck = { version = "1.19.0", features = ["derive"] }
image = { version = "0.25.4", default-features = false ,features = ["png", "jpeg"]}
cgmath = "0.18.0"
tracing-appender = "0.2.3"

egui = "0.29.1"
egui-wgpu = "0.29.1"
egui-winit = "0.29"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pollster = "0.4"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1"
tracing-wasm = "0.2"
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["Document", "Element", "Window"] }
